# version: '3.4'

# services:
#   apigetway:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=8080
#     ports:
#       - "8080"

#   apigetway:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=8080
#     ports:
#       - "8080"

