version: '3.4'

services:
  apigetway:
    image: ${DOCKER_REGISTRY-}apigetway
    build:
      context: .
      dockerfile: ApiGetway/Dockerfile
    ports:
      - 5100:80
    networks:
      - proxybackend
  receivedmoneyservice:
    container_name: demo-blazor-app
    image: ${DOCKER_REGISTRY-}receivedmoneyservice
    build:
      context: .
      dockerfile: ReceivedMoneyService/Dockerfile
    ports:
      - 5200:80
    networks:
      - proxybackend



networks:
  proxybackend:
   name: proxybackend
   driver: bridge

